### ISSUE TITLE
exit(badarg) is confusing and non-standard?

### ISSUE THREAD

**Issue by ferd** [okeuday/uuid#14]
The uuid codebase uses `exit(badarg)` in multiple places, which can be a bit confusing (see: https://github.com/okeuday/uuid/blob/master/src/uuid.erl#L960-L961)

The OTP library seems to always use `error(badarg)` (or `error(badarg, Reason)`), by comparison:
```
→ ack -r 'exit\(badarg' | grep badarg | wc -l
      20
→ ack -r 'error\(badarg' | grep badarg | wc -l
     355
```
half of the 20 calls are in the `inet` stack and are converted to `{error, badarg}` as a return value.

The semantics I'm used to (and those can be debated) is that:
- `throw` stands for non-local returns to be caught within a module scope, and shouldn't be exposed to the user, but are useful as a control-flow mechanism within a specific context.
- `error` are for programming exceptions related to user errors, and that interrupt the flow of a program
- `exit` exceptions are specifically for the handling of issues that keep the current process from running and which the user wouldn't be expected to handle (such as a parent or peer process dying, or a message directly indicating the process should terminate)

Historically `exit`s have been using in the days prior to `try ... catch` where `catch Expression` was the only mechanism, as a way to avoid building a stacktrace. `try ... catch` now makes this optional through `erlang:get_stacktrace()`, so that optimization shouldn't be required anymore.

Would it make sense for this library to change its usage of `exit(badarg)` into `error(badarg)` in an attempt to stay in line with the usual OTP mechanisms, and avoid nasty surprises? It can be argued that changing the type will probably be a surprise to established users, but I leave this up to the maintainers to decide.

**Comment by elbrujohalcon** [comment]
:+1:

**Comment by okeuday** [comment]
I created a tag with the most recent commit as `v1.5.0.1` which can help people avoid the change until they are ready to get the update.  I can add the update to use `error(badarg)` instead of `exit(badarg)` due to that approach being more correct.

**Comment by okeuday** [comment]
Sorry to contradict myself, but this change should not occur due to the extra latency using error instead of exit adds because error automatically includes the stacktrace.  An old complaint about this in a completely different context is http://erlang.org/pipermail/erlang-questions/2013-November/075928.html .  Using `exit(badarg)` is uncommon based on the existing Erlang/OTP source code, but it is a more efficient approach since the stacktrace is not being used when `badarg` is the reason for the exception.

The `badarg` is either due to a developer error that should be fixed, or is an exception that wants to be handled for other source code to execute.  In either case the `badarg` exception doesn't need the stacktrace since it will naturally get one at a higher level, if the exception is allowed to kill the process.  The `uuid` source code is focusing on efficiency (`quickrand` and `trie` also use `exit(badarg)` due to focusing on efficiency), so it is better to not use `error(badarg)` to avoid the added latency when getting the stacktrace (especially when the stacktrace is normally not used with a badarg).

**Comment by okeuday** [comment]
If you doubt this, try `catch error(badarg).`

**Comment by ferd** [comment]
This is covered in my point:

> Historically `exit`s have been using in the days prior to `try ... catch` where `catch Expression` was the only mechanism, as a way to avoid building a stacktrace. `try ... catch` now makes this optional through `erlang:get_stacktrace()`, so that optimization shouldn't be required anymore.

Check the post you're linking to, it mentions the same point. If you're performance-conscious. Use `try...catch` and omit the stacktrace generation. It is more flexible than just `catch Expression`. Specifically:

> If a catch clause matches, execution just continues and no extra cost is 
incurred as long as you don't try to inspect the stack trace. If none of 
the clauses match, the only cost was that of trying the clause patterns 
and guards. 
> [...]
>  *But* if someone wants to actually look at the stack trace of the 
exception, the "opaque blob" mentioned above must be reified as an 
Erlang term, by calling erlang:get_stacktrace().
> [...]
> So the general advice is: Don't call erlang:get_stacktrace() just 
because you can. If you don't have a real reason for catching every 
possible exception, just let the uninteresting ones fall through.

The `catch Expression` form is specifically one example where you auto-generate a stacktrace and one you should avoid. Still from the post you linked, read from the paragraph beginning in:

> Finally, this is also another reason to rewrite old occurrences of 
'catch Expr' into 'try Expr catch ... end', because it basically works 
like this:

I don't believe the latency or efficiency argument holds ground under these circumstances.

**Comment by okeuday** [comment]
@ferd In higher-level source code, there is a chance that `catch` will be being used.  While I don't agree with using `catch` due to the possibility of using `try...catch` now (which is more descriptive, not as dirty), it is possible that `catch` is being used in a way that makes sense (e.g., to prevent a terminate callback from throwing an exception).  It is better to make sure that there is no overhead associated with using `catch`.  The only difference between the two approaches is `exit:badarg` now compared to `error:badarg` within the `try...catch`.

**Comment by ferd** [comment]
Alright. I mean I won't push it further, but anyone who cares about performance should just not use `catch Expr` and then pretend they do care about it.
