### ISSUE TITLE
Using master branch instead of v1.7.2 causes compile failure

### ISSUE THREAD

**Issue by murphyryan1** [okeuday/uuid#22]
When compiling cqerl on elixir I get a compilation error when it tries to compile UUID.  When I add a dependency override to uuid 1.7.2 the error goes away.  I am not sure with which package (cqerl or uuid) the issue lies, but thought I'd mention it.

the error I was getting is:

`\===> Compiling uuid
===> Compiling src/uuid.erl failed
src/uuid.erl:503: call to crypto:rand_bytes/1 will fail, since it was removed in 20.0; use crypto:strong_rand_bytes/1`

`** (Mix) Could not compile dependency :uuid, "/./.mix/rebar3 bare compile --paths "/./_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile uuid", update it with "mix deps.update uuid" or clean it with "mix deps.clean uuid"`

**Comment by okeuday** [comment]
To get that error, you would have been using the tag `v1.5.1` or something previous to that because the call to `crypto:rand_bytes/1` was removed a long time ago (2016-05-16 as shown at https://github.com/okeuday/uuid/commit/4b705b22f5d095970558d904e43c4354bd0e0a7f).  The `master` branch is always ahead of the most recent tag, so `master` has a few small additions after `v1.7.2` was created, but both should work without that error.
