### ISSUE TITLE
Pid format change in Erlang/OTP 23

### ISSUE THREAD

**Issue by lpgauth** [okeuday/uuid#26]
Hi, it looks like the PID format changed in OTP-22 and breaks `uuid:new/2`.

https://github.com/okeuday/uuid/blob/master/src/uuid.erl#L177

```erlang
Erlang/OTP 22 [RELEASE CANDIDATE 2]

rp(erlang:term_to_binary(self())).

<<131,88,100,0,40,114,116,98,45,103,97,116,101,119,97,121,
  64,108,103,97,45,103,97,116,101,119,97,121,45,49,46,115,
  121,115,46,97,100,103,101,97,114,46,99,111,109,0,0,13,
  101,0,0,3,4,0,0,0,2>>
```
vs 

```erlang
Erlang/OTP 21 [erts-10.3.2]

rp(erlang:term_to_binary(self())).

<<131,103,100,0,40,114,116,98,45,103,97,116,101,119,97,
  121,64,108,103,97,45,103,97,116,101,119,97,121,45,50,46,
  115,121,115,46,97,100,103,101,97,114,46,99,111,109,0,0,
  115,205,0,0,5,174,2>>
```

**Comment by lpgauth** [comment]
Doesn't seem documented... 
https://github.com/erlang/otp/blob/OTP-22.0-rc2/erts/doc/src/erl_ext_dist.xml#L461

Could be a regression in OTP-22.

**Comment by okeuday** [comment]
@lpgauth Hi, Thank you for reporting this, the new format was never documented but was added in Erlang/OTP 19.0-rc1 (as shown at https://github.com/erlang/otp/commit/9c80b9ec06fc0ca89dcc8d797a2dbc408a162098#diff-c1a9d2a2e4882ceff50ef831d26288ea) and is now used by default (shown at https://github.com/erlang/otp/commit/78ea501bcc84bd8bd49da97e514c1c3b20682d86), due to an intentional change.  Will need to update this code and the Erlang Binary Term Format implementations based on this.

**Comment by okeuday** [comment]
Updated the issue title based on http://erlang.org/pipermail/erlang-questions/2019-April/097700.html

**Comment by lpgauth** [comment]
It's OTP-22 not OTP-23.

**Comment by okeuday** [comment]
This is fixed (next commit fixed the travis build).
