### ISSUE TITLE
Can't be built with erlang.mk on OTP-20

### ISSUE THREAD

**Issue by tank-bohr** [okeuday/uuid#27]
Makefile

```
PROJECT = hello
PROJECT_DESCRIPTION = New project
PROJECT_VERSION = 0.1.0

DEPS = uuid

include erlang.mk
```

When I run `make deps`

```
 DEP    uuid (master)
 DEP    quickrand (master)
 DEPEND quickrand.d
 ERLC   quickrand.erl quickrand_cache.erl quickrand_cache_normal.erl quickrand_hash.erl quickrand_normal.erl random_wh06_int.erl random_wh82.erl
Old inliner: threshold=0 functions=[{rotate_32,2},
                                    {rotate_64,2},
                                    {consume_32,2},
                                    {consume_32_part,2},
                                    {consume_64,2},
                                    {add_32,2},
                                    {add_32,3},
                                    {add_64,2},
                                    {add_64,3},
                                    {add_64,4},
                                    {add_64,5},
                                    {add_64,6},
                                    {subtract_32,2}]
 APP    quickrand.app.src
 DEPEND uuid.d
 ERLC   uuid.erl
src/uuid.erl:97: -error("Erlang/OTP version invalid").
make[2]: *** [ebin/uuid.app] Error 1
make[1]: *** [app] Error 2
make: *** [deps] Error 2
```

My OTP version is `Erlang/OTP 20 [erts-9.3]`

**Comment by okeuday** [comment]
@tank-bohr I haven't used the erlang.mk approach to building, so I am unsure what broke, but I know the error is due to the Erlang compiler not getting a define based on the Erlang/OTP major version number (i.e., ERLANG_OTP_VERSION_20 at https://github.com/okeuday/uuid/blob/master/rebar.config#L5-L9).  If you used Erlang/OTP >= 21.x, then there wouldn't be an error, due to the Erlang/OTP version being available in the preprocessor for those more recent versions.  If you build with rebar2, rebar3 or mix, those should work fine.  If you have an update to erlang.mk that works, just create a pull request and I can merge it.

**Comment by tank-bohr** [comment]
BTW I just thinking. It would work if you didn't add a makefile. Erlang.mk is smart enough to use rebar if makefile is not available.

**Comment by okeuday** [comment]
@tank-bohr Thanks for the fix.  That is ok to leave the makefile, it provides the erlang.mk usage for people that normally use that for building.
