### ISSUE TITLE
Cached methods using quickrand_cache need to be initialised first

### ISSUE THREAD

**Issue by louiscb** [okeuday/uuid#32]
When calling the cached v4 methods, e.g `:uuid.get_v4(:cached)` you get errors if you don't first initialise the quickrand_cache module , like so: `:quickrand_cache.init()`. It required the user looking through the source code of the quickrand module to do that. I think it would be nice to provide a method inside of :uuid called something along the lines of "init_cache()" and then add documentation that explains the required steps. I'm happy to make this pr.

**Comment by louiscb** [comment]
Ok. What's the intended use case of the cached v4? Since we have to do the quickrand initialisation per process, it adds a lot of overhead and increases the execution time of the uuid generation massively.

**Comment by okeuday** [comment]
I added a description in `quickrand_cache` for its usage.
https://github.com/okeuday/quickrand/blob/2e82140b30bbf548726f98b836bc469cabcfb075/src/quickrand_cache.erl#L7-L18
I also modified the README change to [provide more details](https://github.com/okeuday/uuid#usage).
The usage of `quickrand_cache` would want the cached random data to stick around a long time, so the Erlang process should be long-lived if the `init` function is used.  Otherwise, you should be using the `new` function as described in the new README info.
